const GET_LOANS = 'GET_LOANS';
const GET_LOAN = 'GET_LOAN';
const FETCH_LOANS = 'FETCH_LOANS';
const SET_LOAN_DETAIL = 'SET_LOAN_DETAIL';
const SET_LOANS = 'SET_LOANS';

export {
  GET_LOANS,
  FETCH_LOANS,
  SET_LOAN_DETAIL,
  GET_LOAN,
  SET_LOANS
};
